[project]
name = "gtpr"
version = "0.1.0"
description = "genshin team power ranking"
authors = [
    {name = "r5ne"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "gtpr", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
